spring:
  thymeleaf:
    mode: HTML5
logging:
  level:
    org:
      springframework: error
server:
  port: ${port:8080}

qiniu:
  accessKey: qiniuaccess
  secretKey: qiniusecret
  domain: qiniudomain
